/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthInviteRouteImport } from './routes/auth.invite'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppNovaOsRouteImport } from './routes/app.nova-os'
import { Route as AppMentorRouteImport } from './routes/app.mentor'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAssetsRouteImport } from './routes/app.assets'
import { Route as AppAiDashboardRouteImport } from './routes/app.ai-dashboard'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppNovaIndexRouteImport } from './routes/app.nova.index'
import { Route as AppLaunchpadIndexRouteImport } from './routes/app.launchpad.index'
import { Route as AppBlogIndexRouteImport } from './routes/app.blog.index'
import { Route as AppNovaWorkflowsRouteImport } from './routes/app.nova.workflows'
import { Route as AppNovaReportsRouteImport } from './routes/app.nova.reports'
import { Route as AppNovaLeadsRouteImport } from './routes/app.nova.leads'
import { Route as AppNovaCrmRouteImport } from './routes/app.nova.crm'
import { Route as AppNovaClientsRouteImport } from './routes/app.nova.clients'
import { Route as AppNovaOsSlugRouteImport } from './routes/app.nova-os.$slug'
import { Route as AppLaunchpadHistoryRouteImport } from './routes/app.launchpad.history'
import { Route as AppLaunchpadToolRouteImport } from './routes/app.launchpad.$tool'
import { Route as AppBlogIdRouteImport } from './routes/app.blog.$id'
import { Route as AppBillingReturnRouteImport } from './routes/app.billing.return'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInviteRoute = AuthInviteRouteImport.update({
  id: '/auth/invite',
  path: '/auth/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNovaOsRoute = AppNovaOsRouteImport.update({
  id: '/nova-os',
  path: '/nova-os',
  getParentRoute: () => AppRoute,
} as any)
const AppMentorRoute = AppMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppAiDashboardRoute = AppAiDashboardRouteImport.update({
  id: '/ai-dashboard',
  path: '/ai-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppNovaIndexRoute = AppNovaIndexRouteImport.update({
  id: '/nova/',
  path: '/nova/',
  getParentRoute: () => AppRoute,
} as any)
const AppLaunchpadIndexRoute = AppLaunchpadIndexRouteImport.update({
  id: '/launchpad/',
  path: '/launchpad/',
  getParentRoute: () => AppRoute,
} as any)
const AppBlogIndexRoute = AppBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AppRoute,
} as any)
const AppNovaWorkflowsRoute = AppNovaWorkflowsRouteImport.update({
  id: '/nova/workflows',
  path: '/nova/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppNovaReportsRoute = AppNovaReportsRouteImport.update({
  id: '/nova/reports',
  path: '/nova/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppNovaLeadsRoute = AppNovaLeadsRouteImport.update({
  id: '/nova/leads',
  path: '/nova/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppNovaCrmRoute = AppNovaCrmRouteImport.update({
  id: '/nova/crm',
  path: '/nova/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppNovaClientsRoute = AppNovaClientsRouteImport.update({
  id: '/nova/clients',
  path: '/nova/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppNovaOsSlugRoute = AppNovaOsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppNovaOsRoute,
} as any)
const AppLaunchpadHistoryRoute = AppLaunchpadHistoryRouteImport.update({
  id: '/launchpad/history',
  path: '/launchpad/history',
  getParentRoute: () => AppRoute,
} as any)
const AppLaunchpadToolRoute = AppLaunchpadToolRouteImport.update({
  id: '/launchpad/$tool',
  path: '/launchpad/$tool',
  getParentRoute: () => AppRoute,
} as any)
const AppBlogIdRoute = AppBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingReturnRoute = AppBillingReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => AppBillingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/activity': typeof AppActivityRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai-dashboard': typeof AppAiDashboardRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/billing': typeof AppBillingRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/mentor': typeof AppMentorRoute
  '/app/nova-os': typeof AppNovaOsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app/': typeof AppIndexRoute
  '/app/billing/return': typeof AppBillingReturnRoute
  '/app/blog/$id': typeof AppBlogIdRoute
  '/app/launchpad/$tool': typeof AppLaunchpadToolRoute
  '/app/launchpad/history': typeof AppLaunchpadHistoryRoute
  '/app/nova-os/$slug': typeof AppNovaOsSlugRoute
  '/app/nova/clients': typeof AppNovaClientsRoute
  '/app/nova/crm': typeof AppNovaCrmRoute
  '/app/nova/leads': typeof AppNovaLeadsRoute
  '/app/nova/reports': typeof AppNovaReportsRoute
  '/app/nova/workflows': typeof AppNovaWorkflowsRoute
  '/app/blog/': typeof AppBlogIndexRoute
  '/app/launchpad/': typeof AppLaunchpadIndexRoute
  '/app/nova/': typeof AppNovaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo': typeof DemoRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/activity': typeof AppActivityRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai-dashboard': typeof AppAiDashboardRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/billing': typeof AppBillingRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/mentor': typeof AppMentorRoute
  '/app/nova-os': typeof AppNovaOsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app': typeof AppIndexRoute
  '/app/billing/return': typeof AppBillingReturnRoute
  '/app/blog/$id': typeof AppBlogIdRoute
  '/app/launchpad/$tool': typeof AppLaunchpadToolRoute
  '/app/launchpad/history': typeof AppLaunchpadHistoryRoute
  '/app/nova-os/$slug': typeof AppNovaOsSlugRoute
  '/app/nova/clients': typeof AppNovaClientsRoute
  '/app/nova/crm': typeof AppNovaCrmRoute
  '/app/nova/leads': typeof AppNovaLeadsRoute
  '/app/nova/reports': typeof AppNovaReportsRoute
  '/app/nova/workflows': typeof AppNovaWorkflowsRoute
  '/app/blog': typeof AppBlogIndexRoute
  '/app/launchpad': typeof AppLaunchpadIndexRoute
  '/app/nova': typeof AppNovaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/activity': typeof AppActivityRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai-dashboard': typeof AppAiDashboardRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/billing': typeof AppBillingRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/mentor': typeof AppMentorRoute
  '/app/nova-os': typeof AppNovaOsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app/': typeof AppIndexRoute
  '/app/billing/return': typeof AppBillingReturnRoute
  '/app/blog/$id': typeof AppBlogIdRoute
  '/app/launchpad/$tool': typeof AppLaunchpadToolRoute
  '/app/launchpad/history': typeof AppLaunchpadHistoryRoute
  '/app/nova-os/$slug': typeof AppNovaOsSlugRoute
  '/app/nova/clients': typeof AppNovaClientsRoute
  '/app/nova/crm': typeof AppNovaCrmRoute
  '/app/nova/leads': typeof AppNovaLeadsRoute
  '/app/nova/reports': typeof AppNovaReportsRoute
  '/app/nova/workflows': typeof AppNovaWorkflowsRoute
  '/app/blog/': typeof AppBlogIndexRoute
  '/app/launchpad/': typeof AppLaunchpadIndexRoute
  '/app/nova/': typeof AppNovaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/demo'
    | '/onboarding'
    | '/pricing'
    | '/signup'
    | '/app/activity'
    | '/app/admin'
    | '/app/ai-dashboard'
    | '/app/assets'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/integrations'
    | '/app/leads'
    | '/app/mentor'
    | '/app/nova-os'
    | '/app/settings'
    | '/auth/forgot-password'
    | '/auth/invite'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/app/'
    | '/app/billing/return'
    | '/app/blog/$id'
    | '/app/launchpad/$tool'
    | '/app/launchpad/history'
    | '/app/nova-os/$slug'
    | '/app/nova/clients'
    | '/app/nova/crm'
    | '/app/nova/leads'
    | '/app/nova/reports'
    | '/app/nova/workflows'
    | '/app/blog/'
    | '/app/launchpad/'
    | '/app/nova/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/demo'
    | '/onboarding'
    | '/pricing'
    | '/signup'
    | '/app/activity'
    | '/app/admin'
    | '/app/ai-dashboard'
    | '/app/assets'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/integrations'
    | '/app/leads'
    | '/app/mentor'
    | '/app/nova-os'
    | '/app/settings'
    | '/auth/forgot-password'
    | '/auth/invite'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/app'
    | '/app/billing/return'
    | '/app/blog/$id'
    | '/app/launchpad/$tool'
    | '/app/launchpad/history'
    | '/app/nova-os/$slug'
    | '/app/nova/clients'
    | '/app/nova/crm'
    | '/app/nova/leads'
    | '/app/nova/reports'
    | '/app/nova/workflows'
    | '/app/blog'
    | '/app/launchpad'
    | '/app/nova'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/demo'
    | '/onboarding'
    | '/pricing'
    | '/signup'
    | '/app/activity'
    | '/app/admin'
    | '/app/ai-dashboard'
    | '/app/assets'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/integrations'
    | '/app/leads'
    | '/app/mentor'
    | '/app/nova-os'
    | '/app/settings'
    | '/auth/forgot-password'
    | '/auth/invite'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/app/'
    | '/app/billing/return'
    | '/app/blog/$id'
    | '/app/launchpad/$tool'
    | '/app/launchpad/history'
    | '/app/nova-os/$slug'
    | '/app/nova/clients'
    | '/app/nova/crm'
    | '/app/nova/leads'
    | '/app/nova/reports'
    | '/app/nova/workflows'
    | '/app/blog/'
    | '/app/launchpad/'
    | '/app/nova/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthInviteRoute: typeof AuthInviteRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/invite': {
      id: '/auth/invite'
      path: '/auth/invite'
      fullPath: '/auth/invite'
      preLoaderRoute: typeof AuthInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nova-os': {
      id: '/app/nova-os'
      path: '/nova-os'
      fullPath: '/app/nova-os'
      preLoaderRoute: typeof AppNovaOsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mentor': {
      id: '/app/mentor'
      path: '/mentor'
      fullPath: '/app/mentor'
      preLoaderRoute: typeof AppMentorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets': {
      id: '/app/assets'
      path: '/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-dashboard': {
      id: '/app/ai-dashboard'
      path: '/ai-dashboard'
      fullPath: '/app/ai-dashboard'
      preLoaderRoute: typeof AppAiDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nova/': {
      id: '/app/nova/'
      path: '/nova'
      fullPath: '/app/nova/'
      preLoaderRoute: typeof AppNovaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/launchpad/': {
      id: '/app/launchpad/'
      path: '/launchpad'
      fullPath: '/app/launchpad/'
      preLoaderRoute: typeof AppLaunchpadIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/blog/': {
      id: '/app/blog/'
      path: '/blog'
      fullPath: '/app/blog/'
      preLoaderRoute: typeof AppBlogIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nova/workflows': {
      id: '/app/nova/workflows'
      path: '/nova/workflows'
      fullPath: '/app/nova/workflows'
      preLoaderRoute: typeof AppNovaWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nova/reports': {
      id: '/app/nova/reports'
      path: '/nova/reports'
      fullPath: '/app/nova/reports'
      preLoaderRoute: typeof AppNovaReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nova/leads': {
      id: '/app/nova/leads'
      path: '/nova/leads'
      fullPath: '/app/nova/leads'
      preLoaderRoute: typeof AppNovaLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nova/crm': {
      id: '/app/nova/crm'
      path: '/nova/crm'
      fullPath: '/app/nova/crm'
      preLoaderRoute: typeof AppNovaCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nova/clients': {
      id: '/app/nova/clients'
      path: '/nova/clients'
      fullPath: '/app/nova/clients'
      preLoaderRoute: typeof AppNovaClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nova-os/$slug': {
      id: '/app/nova-os/$slug'
      path: '/$slug'
      fullPath: '/app/nova-os/$slug'
      preLoaderRoute: typeof AppNovaOsSlugRouteImport
      parentRoute: typeof AppNovaOsRoute
    }
    '/app/launchpad/history': {
      id: '/app/launchpad/history'
      path: '/launchpad/history'
      fullPath: '/app/launchpad/history'
      preLoaderRoute: typeof AppLaunchpadHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/launchpad/$tool': {
      id: '/app/launchpad/$tool'
      path: '/launchpad/$tool'
      fullPath: '/app/launchpad/$tool'
      preLoaderRoute: typeof AppLaunchpadToolRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/blog/$id': {
      id: '/app/blog/$id'
      path: '/blog/$id'
      fullPath: '/app/blog/$id'
      preLoaderRoute: typeof AppBlogIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing/return': {
      id: '/app/billing/return'
      path: '/return'
      fullPath: '/app/billing/return'
      preLoaderRoute: typeof AppBillingReturnRouteImport
      parentRoute: typeof AppBillingRoute
    }
  }
}

interface AppBillingRouteChildren {
  AppBillingReturnRoute: typeof AppBillingReturnRoute
}

const AppBillingRouteChildren: AppBillingRouteChildren = {
  AppBillingReturnRoute: AppBillingReturnRoute,
}

const AppBillingRouteWithChildren = AppBillingRoute._addFileChildren(
  AppBillingRouteChildren,
)

interface AppNovaOsRouteChildren {
  AppNovaOsSlugRoute: typeof AppNovaOsSlugRoute
}

const AppNovaOsRouteChildren: AppNovaOsRouteChildren = {
  AppNovaOsSlugRoute: AppNovaOsSlugRoute,
}

const AppNovaOsRouteWithChildren = AppNovaOsRoute._addFileChildren(
  AppNovaOsRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAiDashboardRoute: typeof AppAiDashboardRoute
  AppAssetsRoute: typeof AppAssetsRoute
  AppBillingRoute: typeof AppBillingRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMentorRoute: typeof AppMentorRoute
  AppNovaOsRoute: typeof AppNovaOsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBlogIdRoute: typeof AppBlogIdRoute
  AppLaunchpadToolRoute: typeof AppLaunchpadToolRoute
  AppLaunchpadHistoryRoute: typeof AppLaunchpadHistoryRoute
  AppNovaClientsRoute: typeof AppNovaClientsRoute
  AppNovaCrmRoute: typeof AppNovaCrmRoute
  AppNovaLeadsRoute: typeof AppNovaLeadsRoute
  AppNovaReportsRoute: typeof AppNovaReportsRoute
  AppNovaWorkflowsRoute: typeof AppNovaWorkflowsRoute
  AppBlogIndexRoute: typeof AppBlogIndexRoute
  AppLaunchpadIndexRoute: typeof AppLaunchpadIndexRoute
  AppNovaIndexRoute: typeof AppNovaIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAdminRoute: AppAdminRoute,
  AppAiDashboardRoute: AppAiDashboardRoute,
  AppAssetsRoute: AppAssetsRoute,
  AppBillingRoute: AppBillingRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMentorRoute: AppMentorRoute,
  AppNovaOsRoute: AppNovaOsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBlogIdRoute: AppBlogIdRoute,
  AppLaunchpadToolRoute: AppLaunchpadToolRoute,
  AppLaunchpadHistoryRoute: AppLaunchpadHistoryRoute,
  AppNovaClientsRoute: AppNovaClientsRoute,
  AppNovaCrmRoute: AppNovaCrmRoute,
  AppNovaLeadsRoute: AppNovaLeadsRoute,
  AppNovaReportsRoute: AppNovaReportsRoute,
  AppNovaWorkflowsRoute: AppNovaWorkflowsRoute,
  AppBlogIndexRoute: AppBlogIndexRoute,
  AppLaunchpadIndexRoute: AppLaunchpadIndexRoute,
  AppNovaIndexRoute: AppNovaIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthInviteRoute: AuthInviteRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
