// This file is automatically generated. Do not edit it directly.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      ai_dashboards: {
        Row: {
          biggest_blocker: string | null;
          business: string;
          created_at: string;
          current_revenue: string | null;
          generated_at: string;
          goal: string | null;
          id: string;
          niche: string | null;
          organization_id: string;
          payload: Json;
          stage: string | null;
          target_customer: string | null;
          updated_at: string;
        };
        Insert: {
          biggest_blocker?: string | null;
          business: string;
          created_at?: string;
          current_revenue?: string | null;
          generated_at?: string;
          goal?: string | null;
          id?: string;
          niche?: string | null;
          organization_id: string;
          payload: Json;
          stage?: string | null;
          target_customer?: string | null;
          updated_at?: string;
        };
        Update: {
          biggest_blocker?: string | null;
          business?: string;
          created_at?: string;
          current_revenue?: string | null;
          generated_at?: string;
          goal?: string | null;
          id?: string;
          niche?: string | null;
          organization_id?: string;
          payload?: Json;
          stage?: string | null;
          target_customer?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ai_dashboards_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: true;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      ai_operator_configs: {
        Row: {
          brand_voice_keywords: Json | null;
          created_at: string;
          gtm_strategy_summary: string | null;
          id: string;
          llm_model: string | null;
          llm_prompt_version: string | null;
          operator_name: string | null;
          operator_tone: string | null;
          primary_niche: string | null;
          raw_llm_response: Json | null;
          recommended_tools: Json | null;
          source_intake_id: string | null;
          status: string;
          top_3_pain_points: Json | null;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          brand_voice_keywords?: Json | null;
          created_at?: string;
          gtm_strategy_summary?: string | null;
          id?: string;
          llm_model?: string | null;
          llm_prompt_version?: string | null;
          operator_name?: string | null;
          operator_tone?: string | null;
          primary_niche?: string | null;
          raw_llm_response?: Json | null;
          recommended_tools?: Json | null;
          source_intake_id?: string | null;
          status?: string;
          top_3_pain_points?: Json | null;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          brand_voice_keywords?: Json | null;
          created_at?: string;
          gtm_strategy_summary?: string | null;
          id?: string;
          llm_model?: string | null;
          llm_prompt_version?: string | null;
          operator_name?: string | null;
          operator_tone?: string | null;
          primary_niche?: string | null;
          raw_llm_response?: Json | null;
          recommended_tools?: Json | null;
          source_intake_id?: string | null;
          status?: string;
          top_3_pain_points?: Json | null;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      ai_usage: {
        Row: {
          created_at: string;
          id: string;
          model: string;
          prompt_summary: string | null;
          session_id: string | null;
          tokens_used: number;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          model?: string;
          prompt_summary?: string | null;
          session_id?: string | null;
          tokens_used?: number;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          model?: string;
          prompt_summary?: string | null;
          session_id?: string | null;
          tokens_used?: number;
          user_id?: string;
        };
        Relationships: [];
      };
      automation_drafts: {
        Row: {
          created_at: string;
          description: string;
          id: string;
          status: string;
          updated_at: string;
          user_id: string;
          workflow_json: Json;
        };
        Insert: {
          created_at?: string;
          description: string;
          id?: string;
          status?: string;
          updated_at?: string;
          user_id: string;
          workflow_json: Json;
        };
        Update: {
          created_at?: string;
          description?: string;
          id?: string;
          status?: string;
          updated_at?: string;
          user_id?: string;
          workflow_json?: Json;
        };
        Relationships: [];
      };
      automation_settings: {
        Row: {
          config: Json;
          created_at: string;
          enabled: boolean;
          id: string;
          key: string;
          label: string | null;
          organization_id: string;
          updated_at: string;
        };
        Insert: {
          config?: Json;
          created_at?: string;
          enabled?: boolean;
          id?: string;
          key: string;
          label?: string | null;
          organization_id: string;
          updated_at?: string;
        };
        Update: {
          config?: Json;
          created_at?: string;
          enabled?: boolean;
          id?: string;
          key?: string;
          label?: string | null;
          organization_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "automation_settings_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      client_kpi_metrics: {
        Row: {
          client_id: string | null;
          created_at: string;
          id: string;
          metric_date: string;
          metric_key: string;
          metric_value: number;
          source: string | null;
          user_id: string;
        };
        Insert: {
          client_id?: string | null;
          created_at?: string;
          id?: string;
          metric_date?: string;
          metric_key: string;
          metric_value?: number;
          source?: string | null;
          user_id: string;
        };
        Update: {
          client_id?: string | null;
          created_at?: string;
          id?: string;
          metric_date?: string;
          metric_key?: string;
          metric_value?: number;
          source?: string | null;
          user_id?: string;
        };
        Relationships: [];
      };
      client_reports: {
        Row: {
          client_id: string | null;
          created_at: string;
          id: string;
          kpi_snapshot: Json | null;
          markdown_payload: string | null;
          pdf_url: string | null;
          period_end: string | null;
          period_label: string | null;
          period_start: string | null;
          status: string;
          user_id: string;
        };
        Insert: {
          client_id?: string | null;
          created_at?: string;
          id?: string;
          kpi_snapshot?: Json | null;
          markdown_payload?: string | null;
          pdf_url?: string | null;
          period_end?: string | null;
          period_label?: string | null;
          period_start?: string | null;
          status?: string;
          user_id: string;
        };
        Update: {
          client_id?: string | null;
          created_at?: string;
          id?: string;
          kpi_snapshot?: Json | null;
          markdown_payload?: string | null;
          pdf_url?: string | null;
          period_end?: string | null;
          period_label?: string | null;
          period_start?: string | null;
          status?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      content_outputs: {
        Row: {
          created_at: string;
          id: string;
          payload: Json;
          type: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          payload: Json;
          type: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          payload?: Json;
          type?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      credit_ledger: {
        Row: {
          cost: number;
          created_at: string;
          id: string;
          meta: Json | null;
          tool: string;
          user_id: string;
        };
        Insert: {
          cost: number;
          created_at?: string;
          id?: string;
          meta?: Json | null;
          tool: string;
          user_id: string;
        };
        Update: {
          cost?: number;
          created_at?: string;
          id?: string;
          meta?: Json | null;
          tool?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      generated_assets: {
        Row: {
          created_at: string;
          id: string;
          kind: string;
          metadata: Json;
          mime_type: string | null;
          organization_id: string;
          size_bytes: number | null;
          storage_bucket: string | null;
          storage_path: string | null;
          title: string;
          tool_run_id: string | null;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          kind: string;
          metadata?: Json;
          mime_type?: string | null;
          organization_id: string;
          size_bytes?: number | null;
          storage_bucket?: string | null;
          storage_path?: string | null;
          title: string;
          tool_run_id?: string | null;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          kind?: string;
          metadata?: Json;
          mime_type?: string | null;
          organization_id?: string;
          size_bytes?: number | null;
          storage_bucket?: string | null;
          storage_path?: string | null;
          title?: string;
          tool_run_id?: string | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "generated_assets_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "generated_assets_tool_run_id_fkey";
            columns: ["tool_run_id"];
            isOneToOne: false;
            referencedRelation: "tool_runs";
            referencedColumns: ["id"];
          },
        ];
      };
      health_checks: {
        Row: {
          checked_at: string;
          endpoint_name: string;
          id: string;
          response_time_ms: number | null;
          status: string;
          status_code: number | null;
        };
        Insert: {
          checked_at?: string;
          endpoint_name: string;
          id?: string;
          response_time_ms?: number | null;
          status: string;
          status_code?: number | null;
        };
        Update: {
          checked_at?: string;
          endpoint_name?: string;
          id?: string;
          response_time_ms?: number | null;
          status?: string;
          status_code?: number | null;
        };
        Relationships: [];
      };
      leads: {
        Row: {
          company: string | null;
          created_at: string;
          email: string | null;
          id: string;
          name: string;
          notes: string | null;
          organization_id: string;
          phone: string | null;
          source: string | null;
          stage: Database["public"]["Enums"]["lead_stage"];
          updated_at: string;
          value: number | null;
        };
        Insert: {
          company?: string | null;
          created_at?: string;
          email?: string | null;
          id?: string;
          name: string;
          notes?: string | null;
          organization_id: string;
          phone?: string | null;
          source?: string | null;
          stage?: Database["public"]["Enums"]["lead_stage"];
          updated_at?: string;
          value?: number | null;
        };
        Update: {
          company?: string | null;
          created_at?: string;
          email?: string | null;
          id?: string;
          name?: string;
          notes?: string | null;
          organization_id?: string;
          phone?: string | null;
          source?: string | null;
          stage?: Database["public"]["Enums"]["lead_stage"];
          updated_at?: string;
          value?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "leads_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      n8n_error_log: {
        Row: {
          error_message: string | null;
          error_node: string | null;
          execution_id: string | null;
          id: string;
          occurred_at: string;
          workflow_name: string;
        };
        Insert: {
          error_message?: string | null;
          error_node?: string | null;
          execution_id?: string | null;
          id?: string;
          occurred_at?: string;
          workflow_name: string;
        };
        Update: {
          error_message?: string | null;
          error_node?: string | null;
          execution_id?: string | null;
          id?: string;
          occurred_at?: string;
          workflow_name?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          created_at: string;
          id: string;
          message: string | null;
          read: boolean | null;
          session_id: string | null;
          tool_id: string | null;
          type: string | null;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          message?: string | null;
          read?: boolean | null;
          session_id?: string | null;
          tool_id?: string | null;
          type?: string | null;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          message?: string | null;
          read?: boolean | null;
          session_id?: string | null;
          tool_id?: string | null;
          type?: string | null;
          user_id?: string;
        };
        Relationships: [];
      };
      onboarding_responses: {
        Row: {
          biggest_blocker: string | null;
          business_type: string | null;
          completed: boolean;
          completed_at: string | null;
          created_at: string;
          current_revenue: string | null;
          goal: string | null;
          id: string;
          location: string | null;
          niche: string | null;
          offer: string | null;
          organization_id: string;
          stage: Database["public"]["Enums"]["app_stage"] | null;
          target_customer: string | null;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          biggest_blocker?: string | null;
          business_type?: string | null;
          completed?: boolean;
          completed_at?: string | null;
          created_at?: string;
          current_revenue?: string | null;
          goal?: string | null;
          id?: string;
          location?: string | null;
          niche?: string | null;
          offer?: string | null;
          organization_id: string;
          stage?: Database["public"]["Enums"]["app_stage"] | null;
          target_customer?: string | null;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          biggest_blocker?: string | null;
          business_type?: string | null;
          completed?: boolean;
          completed_at?: string | null;
          created_at?: string;
          current_revenue?: string | null;
          goal?: string | null;
          id?: string;
          location?: string | null;
          niche?: string | null;
          offer?: string | null;
          organization_id?: string;
          stage?: Database["public"]["Enums"]["app_stage"] | null;
          target_customer?: string | null;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "onboarding_responses_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: true;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      operator_memory: {
        Row: {
          content: string;
          created_at: string;
          id: string;
          memory_type: string;
          pruned: boolean | null;
          session_id: string | null;
          tags: string[] | null;
          user_id: string;
        };
        Insert: {
          content: string;
          created_at?: string;
          id?: string;
          memory_type?: string;
          pruned?: boolean | null;
          session_id?: string | null;
          tags?: string[] | null;
          user_id: string;
        };
        Update: {
          content?: string;
          created_at?: string;
          id?: string;
          memory_type?: string;
          pruned?: boolean | null;
          session_id?: string | null;
          tags?: string[] | null;
          user_id?: string;
        };
        Relationships: [];
      };
      operator_prompts: {
        Row: {
          component: string;
          created_at: string;
          id: string;
          is_known_component: boolean | null;
          system_prompt: string;
          updated_at: string;
          version: string;
        };
        Insert: {
          component: string;
          created_at?: string;
          id?: string;
          is_known_component?: boolean | null;
          system_prompt: string;
          updated_at?: string;
          version?: string;
        };
        Update: {
          component?: string;
          created_at?: string;
          id?: string;
          is_known_component?: boolean | null;
          system_prompt?: string;
          updated_at?: string;
          version?: string;
        };
        Relationships: [];
      };
      operator_sessions: {
        Row: {
          clarification_sent: boolean | null;
          clarification_text: string | null;
          created_at: string;
          id: string;
          last_confidence: number | null;
          message: string | null;
          session_id: string;
          top_intents: Json | null;
          type: string | null;
          updated_at: string;
          user_id: string | null;
        };
        Insert: {
          clarification_sent?: boolean | null;
          clarification_text?: string | null;
          created_at?: string;
          id?: string;
          last_confidence?: number | null;
          message?: string | null;
          session_id: string;
          top_intents?: Json | null;
          type?: string | null;
          updated_at?: string;
          user_id?: string | null;
        };
        Update: {
          clarification_sent?: boolean | null;
          clarification_text?: string | null;
          created_at?: string;
          id?: string;
          last_confidence?: number | null;
          message?: string | null;
          session_id?: string;
          top_intents?: Json | null;
          type?: string | null;
          updated_at?: string;
          user_id?: string | null;
        };
        Relationships: [];
      };
      organization_members: {
        Row: {
          created_at: string;
          id: string;
          organization_id: string;
          role: Database["public"]["Enums"]["org_role"];
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          organization_id: string;
          role?: Database["public"]["Enums"]["org_role"];
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          organization_id?: string;
          role?: Database["public"]["Enums"]["org_role"];
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "organization_members_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      organizations: {
        Row: {
          business_type: string | null;
          created_at: string;
          owner_id: string;
          goal: string | null;
          id: string;
          location: string | null;
          name: string;
          niche: string | null;
          offer: string | null;
          stage: Database["public"]["Enums"]["business_stage"];
          target_customer: string | null;
          updated_at: string;
        };
        Insert: {
          business_type?: string | null;
          created_at?: string;
          owner_id: string;
          goal?: string | null;
          id?: string;
          location?: string | null;
          name: string;
          niche?: string | null;
          offer?: string | null;
          stage?: Database["public"]["Enums"]["business_stage"];
          target_customer?: string | null;
          updated_at?: string;
        };
        Update: {
          business_type?: string | null;
          created_at?: string;
          created_by?: string;
          goal?: string | null;
          id?: string;
          location?: string | null;
          name?: string;
          niche?: string | null;
          offer?: string | null;
          stage?: Database["public"]["Enums"]["business_stage"];
          target_customer?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      plan_tier_limits: {
        Row: {
          allowed_tools: Json;
          created_at: string;
          monthly_generation_limit: number | null;
          plan: Database["public"]["Enums"]["plan_tier"];
          price_usd: number;
        };
        Insert: {
          allowed_tools?: Json;
          created_at?: string;
          monthly_generation_limit?: number | null;
          plan: Database["public"]["Enums"]["plan_tier"];
          price_usd?: number;
        };
        Update: {
          allowed_tools?: Json;
          created_at?: string;
          monthly_generation_limit?: number | null;
          plan?: Database["public"]["Enums"]["plan_tier"];
          price_usd?: number;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          avatar_url: string | null;
          created_at: string;
          email: string;
          full_name: string | null;
          id: string;
          onboarding_complete: boolean;
          updated_at: string;
        };
        Insert: {
          avatar_url?: string | null;
          created_at?: string;
          email: string;
          full_name?: string | null;
          id: string;
          onboarding_complete?: boolean;
          updated_at?: string;
        };
        Update: {
          avatar_url?: string | null;
          created_at?: string;
          email?: string;
          full_name?: string | null;
          id?: string;
          onboarding_complete?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      subscriptions: {
        Row: {
          cancel_at_period_end: boolean;
          created_at: string;
          current_period_end: string | null;
          id: string;
          organization_id: string;
          plan: Database["public"]["Enums"]["plan_tier"];
          status: Database["public"]["Enums"]["subscription_status"];
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          updated_at: string;
        };
        Insert: {
          cancel_at_period_end?: boolean;
          created_at?: string;
          current_period_end?: string | null;
          id?: string;
          organization_id: string;
          plan?: Database["public"]["Enums"]["plan_tier"];
          status?: Database["public"]["Enums"]["subscription_status"];
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          updated_at?: string;
        };
        Update: {
          cancel_at_period_end?: boolean;
          created_at?: string;
          current_period_end?: string | null;
          id?: string;
          organization_id?: string;
          plan?: Database["public"]["Enums"]["plan_tier"];
          status?: Database["public"]["Enums"]["subscription_status"];
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "subscriptions_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: true;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      support_tickets: {
        Row: {
          created_at: string;
          id: string;
          issue_summary: string;
          session_id: string | null;
          status: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          issue_summary: string;
          session_id?: string | null;
          status?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          issue_summary?: string;
          session_id?: string | null;
          status?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      tool_outputs: {
        Row: {
          created_at: string;
          formatted_output: string | null;
          id: string;
          output_type: string;
          raw_output: string | null;
          read: boolean | null;
          session_id: string | null;
          tool_id: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          formatted_output?: string | null;
          id?: string;
          output_type?: string;
          raw_output?: string | null;
          read?: boolean | null;
          session_id?: string | null;
          tool_id: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          formatted_output?: string | null;
          id?: string;
          output_type?: string;
          raw_output?: string | null;
          read?: boolean | null;
          session_id?: string | null;
          tool_id?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      tool_runs: {
        Row: {
          completed_at: string | null;
          created_at: string;
          duration_ms: number | null;
          error: string | null;
          feedback: string | null;
          feedback_at: string | null;
          id: string;
          input: Json;
          organization_id: string;
          output: Json | null;
          status: Database["public"]["Enums"]["tool_run_status"];
          surface: Database["public"]["Enums"]["tool_surface"];
          title: string | null;
          tokens_used: number | null;
          tool_key: string;
          user_id: string;
        };
        Insert: {
          completed_at?: string | null;
          created_at?: string;
          duration_ms?: number | null;
          error?: string | null;
          feedback?: string | null;
          feedback_at?: string | null;
          id?: string;
          input?: Json;
          organization_id: string;
          output?: Json | null;
          status?: Database["public"]["Enums"]["tool_run_status"];
          surface: Database["public"]["Enums"]["tool_surface"];
          title?: string | null;
          tokens_used?: number | null;
          tool_key: string;
          user_id: string;
        };
        Update: {
          completed_at?: string | null;
          created_at?: string;
          duration_ms?: number | null;
          error?: string | null;
          feedback?: string | null;
          feedback_at?: string | null;
          id?: string;
          input?: Json;
          organization_id?: string;
          output?: Json | null;
          status?: Database["public"]["Enums"]["tool_run_status"];
          surface?: Database["public"]["Enums"]["tool_surface"];
          title?: string | null;
          tokens_used?: number | null;
          tool_key?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tool_runs_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      usage_tracking: {
        Row: {
          count: number;
          created_at: string;
          id: string;
          organization_id: string;
          period: string;
          tool_key: string;
          updated_at: string;
        };
        Insert: {
          count?: number;
          created_at?: string;
          id?: string;
          organization_id: string;
          period: string;
          tool_key: string;
          updated_at?: string;
        };
        Update: {
          count?: number;
          created_at?: string;
          id?: string;
          organization_id?: string;
          period?: string;
          tool_key?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "usage_tracking_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      user_ai_config: {
        Row: {
          brand_voice: Json | null;
          company_name: string | null;
          created_at: string;
          icp: Json | null;
          logo_url: string | null;
          niche: string | null;
          primary_color: string | null;
          tone: string | null;
          updated_at: string;
          user_id: string;
          value_props: Json | null;
          writing_style: string | null;
        };
        Insert: {
          brand_voice?: Json | null;
          company_name?: string | null;
          created_at?: string;
          icp?: Json | null;
          logo_url?: string | null;
          niche?: string | null;
          primary_color?: string | null;
          tone?: string | null;
          updated_at?: string;
          user_id: string;
          value_props?: Json | null;
          writing_style?: string | null;
        };
        Update: {
          brand_voice?: Json | null;
          company_name?: string | null;
          created_at?: string;
          icp?: Json | null;
          logo_url?: string | null;
          niche?: string | null;
          primary_color?: string | null;
          tone?: string | null;
          updated_at?: string;
          user_id?: string;
          value_props?: Json | null;
          writing_style?: string | null;
        };
        Relationships: [];
      };
      user_integrations: {
        Row: {
          created_at: string;
          encrypted_value: string | null;
          id: string;
          integration_key: string;
          status: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          encrypted_value?: string | null;
          id?: string;
          integration_key: string;
          status?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          encrypted_value?: string | null;
          id?: string;
          integration_key?: string;
          status?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      user_roles: {
        Row: {
          id: string;
          role: Database["public"]["Enums"]["app_role"];
          user_id: string;
        };
        Insert: {
          id?: string;
          role?: Database["public"]["Enums"]["app_role"];
          user_id: string;
        };
        Update: {
          id?: string;
          role?: Database["public"]["Enums"]["app_role"];
          user_id?: string;
        };
        Relationships: [];
      };
      website_analyses: {
        Row: {
          created_at: string;
          error: string | null;
          id: string;
          organization_id: string;
          result: Json | null;
          status: string;
          updated_at: string;
          url: string;
        };
        Insert: {
          created_at?: string;
          error?: string | null;
          id?: string;
          organization_id: string;
          result?: Json | null;
          status?: string;
          updated_at?: string;
          url: string;
        };
        Update: {
          created_at?: string;
          error?: string | null;
          id?: string;
          organization_id?: string;
          result?: Json | null;
          status?: string;
          updated_at?: string;
          url?: string;
        };
        Relationships: [
          {
            foreignKeyName: "website_analyses_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      workflow_logs: {
        Row: {
          created_at: string;
          error_message: string | null;
          execution_id: string;
          id: string;
          log_type: string;
          timestamp: string;
          workflow_name: string;
        };
        Insert: {
          created_at?: string;
          error_message?: string | null;
          execution_id?: string;
          id?: string;
          log_type: string;
          timestamp?: string;
          workflow_name?: string;
        };
        Update: {
          created_at?: string;
          error_message?: string | null;
          execution_id?: string;
          id?: string;
          log_type?: string;
          timestamp?: string;
          workflow_name?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      ai_operator_config: {
        Row: {
          brand_voice_keywords: Json | null;
          created_at: string | null;
          gtm_strategy_summary: string | null;
          id: string | null;
          llm_model: string | null;
          llm_prompt_version: string | null;
          operator_name: string | null;
          operator_tone: string | null;
          primary_niche: string | null;
          raw_llm_response: Json | null;
          recommended_tools: Json | null;
          source_intake_id: string | null;
          status: string | null;
          top_3_pain_points: Json | null;
          updated_at: string | null;
          user_id: string | null;
        };
        Insert: {
          brand_voice_keywords?: Json | null;
          created_at?: string | null;
          gtm_strategy_summary?: string | null;
          id?: string | null;
          llm_model?: string | null;
          llm_prompt_version?: string | null;
          operator_name?: string | null;
          operator_tone?: string | null;
          primary_niche?: string | null;
          raw_llm_response?: Json | null;
          recommended_tools?: Json | null;
          source_intake_id?: string | null;
          status?: string | null;
          top_3_pain_points?: Json | null;
          updated_at?: string | null;
          user_id?: string | null;
        };
        Update: {
          brand_voice_keywords?: Json | null;
          created_at?: string | null;
          gtm_strategy_summary?: string | null;
          id?: string | null;
          llm_model?: string | null;
          llm_prompt_version?: string | null;
          operator_name?: string | null;
          operator_tone?: string | null;
          primary_niche?: string | null;
          raw_llm_response?: Json | null;
          recommended_tools?: Json | null;
          source_intake_id?: string | null;
          status?: string | null;
          top_3_pain_points?: Json | null;
          updated_at?: string | null;
          user_id?: string | null;
        };
        Relationships: [];
      };
      user_credit_balance: {
        Row: {
          credits_remaining: number | null;
          credits_used: number | null;
          starting_credits: number | null;
          user_id: string | null;
        };
        Relationships: [];
      };
      user_integrations_masked: {
        Row: {
          created_at: string | null;
          id: string | null;
          integration_key: string | null;
          is_connected: boolean | null;
          status: string | null;
          updated_at: string | null;
          user_id: string | null;
          value_last4: string | null;
        };
        Insert: {
          created_at?: string | null;
          id?: string | null;
          integration_key?: string | null;
          is_connected?: never;
          status?: string | null;
          updated_at?: string | null;
          user_id?: string | null;
          value_last4?: never;
        };
        Update: {
          created_at?: string | null;
          id?: string | null;
          integration_key?: string | null;
          is_connected?: never;
          status?: string | null;
          updated_at?: string | null;
          user_id?: string | null;
          value_last4?: never;
        };
        Relationships: [];
      };
      users: {
        Row: {
          created_at: string | null;
          email: string | null;
          organization_id: string | null;
          plan_tier: string | null;
          plan_tier_enum: string | null;
          user_id: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "subscriptions_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: true;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Functions: {
      get_org_entitlements: {
        Args: { _org_id: string };
        Returns: {
          plan: string;
          price_usd: number;
          monthly_generation_limit: number | null;
          allowed_tools: string[];
        }[];
      };
      get_user_plan: { Args: { _org_id: string }; Returns: string };
      has_role: {
        Args: {
          _role: Database["public"]["Enums"]["app_role"];
          _user_id: string;
        };
        Returns: boolean;
      };
      is_org_admin: {
        Args: { _org_id: string; _user_id: string };
        Returns: boolean;
      };
      is_org_member: {
        Args: { _org_id: string; _user_id: string };
        Returns: boolean;
      };
    };
    Enums: {
      app_plan: "Starter" | "Launch" | "Operate" | "Scale";
      app_role: "user" | "admin";
      app_stage: "Idea" | "Validate" | "Launch" | "Operate" | "Scale";
      business_stage: "Idea" | "Validate" | "Launch" | "Operate" | "Scale";
      lead_stage: "New" | "Contacted" | "Qualified" | "Proposal" | "Won" | "Lost";
      org_role: "owner" | "admin" | "member";
      plan_tier: "starter" | "launch" | "operate" | "scale";
      subscription_status: "trialing" | "active" | "past_due" | "canceled" | "incomplete";
      tool_run_status: "queued" | "running" | "succeeded" | "failed";
      tool_surface: "launchpad" | "nova";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      app_plan: ["Starter", "Launch", "Operate", "Scale"],
      app_role: ["user", "admin"],
      app_stage: ["Idea", "Validate", "Launch", "Operate", "Scale"],
      business_stage: ["Idea", "Validate", "Launch", "Operate", "Scale"],
      lead_stage: ["New", "Contacted", "Qualified", "Proposal", "Won", "Lost"],
      org_role: ["owner", "admin", "member"],
      plan_tier: ["starter", "launch", "operate", "scale"],
      subscription_status: ["trialing", "active", "past_due", "canceled", "incomplete"],
      tool_run_status: ["queued", "running", "succeeded", "failed"],
      tool_surface: ["launchpad", "nova"],
    },
  },
} as const;
